server:
  port: 8091

# Vault 知识库配置
vault:
  path: D:/Obisidian/ObsProject/QA Agent 开发
  retrieval-top-k: 5
  chunk-max-size: 2000

# DeepSeek 作为基础对话模型以及 Embedding 模型
deepSeek:
  model: "deepseek-v4-pro"
  base-url: "https://api.deepseek.com"
  api-key: "sk-7416cf0764fa4a89851fc611b4a9eec4"

# 日志
logging:
  level:
    cn.pumluda: debug
    dev.langchain4j: debug
  config: classpath:logback-spring.xml