version: '3.8'
# docker-compose -f docker-compose-env.yml -f docker-compose-app.yml up -d
services:
  doc-Agent:
    image: docker.io/system/doc-Agent-app:1.0-SNAPSHOT
    container_name: doc-Agent
    restart: on-failure
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
    volumes:
      - ./log:/data/log
      - ./prompts:/app/docs/prompts
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

  frontend:
    build: ./nginx
    container_name: QA-Agent-frontend
    restart: always
    ports:
      - "9090:80"
    depends_on:
      - QA-Agent
    networks:
      - my-network

networks:
  my-network:
    driver: bridge